// GERADO por scripts/build-semantic.ts a partir de src/design/tokens.json. NÃO editar à mão.
// Papéis (Semantic) disponíveis para os primitivos. Componentes consomem ESTES,
// nunca a Foundation direto (DS-100). Para o valor: sem("color.text.primary").

export const semanticRoles = [
  "color.analytics",
  "color.border.control",
  "color.border.default",
  "color.border.focus",
  "color.border.strong",
  "color.border.subtle",
  "color.critical",
  "color.critical-surface",
  "color.health.attention",
  "color.health.critical",
  "color.health.empty",
  "color.health.healthy",
  "color.information",
  "color.information-surface",
  "color.neutral",
  "color.origin.erp",
  "color.origin.estimate",
  "color.origin.operator",
  "color.precision.high",
  "color.precision.low",
  "color.precision.medium",
  "color.priority.high",
  "color.priority.low",
  "color.priority.medium",
  "color.success",
  "color.success-surface",
  "color.surface.canvas",
  "color.surface.default",
  "color.surface.overlay",
  "color.surface.raised",
  "color.surface.sunken",
  "color.text.disabled",
  "color.text.inverse",
  "color.text.on-accent",
  "color.text.primary",
  "color.text.secondary",
  "color.text.tertiary",
  "color.timeline",
  "color.warning",
  "color.warning-surface",
  "elevation.floating.surface",
  "elevation.flush.surface",
  "elevation.raised.surface",
  "elevation.surface.border",
  "elevation.surface.surface",
  "shadow.color",
  "shadow.floating.color",
  "shadow.overlay.color",
  "shadow.raised.color",
  "state.critical",
  "state.disabled.text",
  "state.hover.motion",
  "type.body-l.size",
  "type.body-l.weight",
  "type.body-m.size",
  "type.body-m.weight",
  "type.body-s.size",
  "type.body-s.weight",
  "type.caption.size",
  "type.caption.weight",
  "type.display.size",
  "type.display.weight",
  "type.label.size",
  "type.label.weight",
  "type.mono.size",
  "type.mono.weight",
  "type.title-l.size",
  "type.title-l.weight",
  "type.title-m.size",
  "type.title-m.weight",
  "type.title-s.size",
  "type.title-s.weight"
] as const;

export type SemanticRole = (typeof semanticRoles)[number];

/** Referência CSS de um papel Semantic: sem("color.text.primary") → "var(--sem-color-text-primary)". */
export function sem(role: SemanticRole): string {
  return `var(--sem-${role.replace(/\./g, "-")})`;
}
